### ISSUE TITLE
Implement getData method for functions

### ISSUE THREAD

**Issue by LogvinovLeon** [trufflesuite/truffle-contract#10]
https://github.com/ethereum/wiki/wiki/JavaScript-API#contract-methods
```
// Get the call data, so you can call the contract through some other means
var myCallData = myContractInstance.myMethod.getData(param1 [, param2, ...]);
// myCallData = '0x45ff3ff6000000000004545345345345..'
```

**Comment by LogvinovLeon** [comment]
One can just use .contract to access the underlying web3 contracts and go from there. Closing now.

**Comment by tymat** [comment]
there's now 

```
yourContractInstance.yourMethod.request(yourMethodParams,..);
```

This will return something like:

```
{ method: 'eth_sendTransaction',
  callback: undefined,
  params:
   [ { to: '0x9538781810e67913f13a56b891452e3aa8dd3ea0',
       data: '0x1d834a1b00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001' } ],
  format: [Function: bound ] }
```

**Comment by beether** [comment]
@tymat do you have any idea why "params" is an array of size 1?  Is there ever a case where it is more than 1 item?

**Comment by beether** [comment]
Why are all of the web3 JS libraries so god awful...

**Comment by LogvinovLeon** [comment]
Params is the array, because that's the specification for JSON PRC. For that method - it's always one element, but in generic case - it's more.
