### ISSUE TITLE
web3 1.0 revert() error message changes depending on network

### ISSUE THREAD

**Issue by RobertoC27** [trufflesuite/truffle-contract#119]
I'm currently working with darq-truffle as i has support for web3 1.0 as suggested here https://github.com/trufflesuite/truffle-contract/issues/56. Developed my contract and tested it using ```darq-truffle develop``` and my tests were completed with no issues. When i change to ```darq-truffle console``` and interacted with my test-net, tests failed. 
I've removed the catch statements and below is the error message when executed with ```darq-truffle develop``` is the following, which is what i was expecting based on [how to catch a revert statement](https://ethereum.stackexchange.com/questions/48627/how-to-catch-revert-error-in-truffle-test-javascript)

![image](https://user-images.githubusercontent.com/8262009/40693399-6a9b5c22-6374-11e8-90fe-fb90ed015306.png)

Now when running tests with my test-network
```darq-truffle console```
![image](https://user-images.githubusercontent.com/8262009/40693461-b8ed897c-6374-11e8-901e-42cdc3b45013.png)

Any idea why this is happening?
my darq-truffle version
![image](https://user-images.githubusercontent.com/8262009/40693498-e578c0d8-6374-11e8-8ff1-435dc6c07c5e.png)

**Comment by RobertoC27** [comment]
@cgewecke Thanks again! It works
![image](https://user-images.githubusercontent.com/8262009/40745664-4e245872-6415-11e8-9d43-28b8f32e19e2.png)

but is there any other way i could check for this kind of 'expected' errors (other than inspecting error messages)?

**Comment by cgewecke** [comment]
@RobertoC27 Sort of!  You can look at the `receipt` object which is attached to the error and inspect the `status` field.
```javascript
try {
  await myContract.methodThatThrows()
} catch(err){
  assert(parseInt(err.receipt.status) === 0)
} 
```

Unfortunately there's some confusion about how the status should be encoded at the moment - the version of web3 `darq-truffle` uses (beta.33) returns a hex string. But beta.34 has started to return a boolean and I believe `ganache-core` is still working out how to sync up with this version. 

Related issue [here](https://github.com/ethereum/web3.js/issues/1657). This is one reason why everything is beta & darq .....

**Comment by RobertoC27** [comment]
@cgewecke thanks for the code snippet. I just installed beta.34 for my frontend, thanks for the heads up. Going to keep an eye on that issue. btw so far I've had no issues with the darq version, other than the memory leak warning, good job with it!
