### ISSUE TITLE
Leaking XMLHttpRequest into the global scope

### ISSUE THREAD

**Issue by fabioberger** [trufflesuite/truffle-contract#14]
Current behaviour:
After requiring `truffle-contract`, global.XMLHttpRequest is defined. Before the require it wasn't. 

Expected behaviour:
Requiring `truffle-contract` should not add properties to the global scope.

**Comment by tcoulter** [comment]
My bet is this is Web3. I need to look into it, but truffle-contract doesn't use XMLHttpRequest directly.

**Comment by fabioberger** [comment]
Yup, just confirmed that it is indeed Web3.js, will open an issue with them. Thanks for looking into it!

**Comment by wtam** [comment]
I need to set my HttpProvider after requiring truffle-contract in nodejs.  Currently I set its via the setProvider call but its only set it to the current provider but not the HttpProvider.  How can I update its.  FYI I'm using windows OS and has major problem with web3, truffle-providers npm install.  So I've to find a way to leverage the truffle-contract
