### ISSUE TITLE
Contract creation with `at` is too slow for long contracts

### ISSUE THREAD

**Issue by LogvinovLeon** [trufflesuite/truffle-contract#16]
My contract is pretty big and when I'm getting an instance using `Contract.deployed()` it works great.

The problem is that I'm storing the address of the contract in an other contract, so I'm forced to use `Contract.at()`.

The difference is that when I'm using `at` it calls `getCode` and then converts the resulting hex string to `BigNumber` just to check if it's zero.

[Here is the line I'm talking about:](https://github.com/trufflesuite/truffle-contract/blob/master/contract.js#L401)

The number has 30000 digits and converting it from hex to decimal causes `toBaseOut` call in bignum library, which is not optimized.

It takes around 20s in browser and during this time the main thread is blocked and UI is not responding.

Are there any other faster methods to check if a hex string is zero, that do . ot require an enourmous amount of modulo divisions?

You can try to run this code to get the feeling of how slow it could be:
```
const BigNumber = require("bignumber.js");
new BigNumber("0x" + "f".repeat(30000));
```

**Comment by tcoulter** [comment]
This was a great catch - I hadn't realized this at all. Easiest way to check for zeroes without modulo division is to probably use a built in method to reduce the input space, then do a string comparison. Perhaps something like this.

```javascript
var code = "0x....";

// Remove 0x prefix
code = code.replace("0x", "");

// Remove all zeroes
code = code.replace(/0/g, "");

// If we have the empty string, code == 0x0
if (code == "") {
  // ...
}
```

**Comment by gnidan** [comment]
(Was looking into this but now waiting until @tcoulter moves tests around to make it easier)

**Comment by tcoulter** [comment]
@gnidan Forgot to mention: A pull request for this bug should be made against `master`. We'll want it on `develop` too, but this is a fix we can push out immediately.

**Comment by elenadimitrova** [comment]
Confirming this fixed the performance issues we were having as well where a suite of 68 UI test scenarios was taking ~90 min to complete, now this is back to pre-truffle-3 timespan of ~30 min.
Thanks for the fix @LogvinovLeon @tcoulter !

**Comment by tcoulter** [comment]
A new version of `truffle-contract` has been pushed, v2.0.1, which includes a fix for this bug. To get this version in Truffle, uninstall and then reinstall Truffle to ensure dependencies are updated. 

Thanks all!
