### ISSUE TITLE
Update web3 to ^0.19.0

### ISSUE THREAD

**Issue by LogvinovLeon** [trufflesuite/truffle-contract#29]
New version of `web3` was released.
Could we update dependencies and publish the new version?
Also update dependency to `truffle-blockchain-utils` when the same issue is fixed there.

**Comment by adonley** [comment]
@LogvinovLeon this actually needs to be updated to **0.19.1**, see https://github.com/ethereum/web3.js/issues/904 . Would you resubmit your pull request with the new dep?

**Comment by tcoulter** [comment]
This is being tracked in #486. Thanks!
