### ISSUE TITLE
web3js dependency ^0.18.0 is broken

### ISSUE THREAD

**Issue by adonley** [trufflesuite/truffle-contract#31]
The web3js dependency on **^0.18.0** needs to be upgraded to **0.19.1** see https://github.com/ethereum/web3.js/issues/904 .

**Comment by mattcarp** [comment]
Temporary fix until this package and `truffle-blockchain-utils` have web3 dependencies updated to 0.19.1:

- Download this package and  [truffle-blockchain-utils ](https://github.com/trufflesuite/truffle-blockchain-utils)to your machine (remove '-master' from the directory name)
- In the package.json for this package, change the web3 dependency to 0.19.1: `"web3": "^0.19.1"`
- Also in the same package.json, change the dependency for `truffle-blockchain-utils` to point to your locally-download version of that package. If you placed them next to each other, this is: `    "truffle-blockchain-utils": "../truffle-blockchain-utils",` 
- In the package.json for truffle-blockchain-utils, change the web3 dependency as in the second step
- From your project's directory, install the local version of this package: `npm install /local/path/to/truffle-contract`

**Comment by dylanseago** [comment]
I created https://github.com/trufflesuite/truffle-contract/pull/32 for this but it depends on https://github.com/trufflesuite/truffle-blockchain-utils/pull/4 being released as a hotfix.

**Comment by tcoulter** [comment]
Closing as duplicate. Using trufflesuite/truffle#485 to track. Thanks!
