### ISSUE TITLE
new(["hello world parameter"],[]) does not work for me

### ISSUE THREAD

**Issue by otembajelle** [trufflesuite/truffle-contract#51]
I hate to bother you for my issue appears to be my wrong usage. After hours of trying, I lost my options and have no alternative left other than consulting the experts.

Environment:
TestRpc and truffle-contract on Eclipse node.js.

Problem:
1. The instance (contract) is created, but the constructor parameter appears to be ignored.
2. The second parameter array (tx-parameters) should be optional but I get an an exception when I leave it out. So the empty [] when calling new() is a workaround.  

I expect:
A new contract in TestRpc with its state (engravedText) set to "hello world". 

Result:
The new contract shows in the TestRpc-console, I can read its state, but it shows an empty string.

```
contract Eternal {
    string engravedText;

    function Eternal(string text) {
    	engravedText = text;
    }

    function getEngravedText() constant returns (string) {
    	return engravedText;
    }

}


```
My code:
```
var provider = new Web3.providers.HttpProvider("http://localhost:8545");
var contract = require("truffle-contract");
// json from Truffle build
var MyContract = contract({
  abi: ...,
  unlinked_binary: ...,
})
MyContract.setProvider(provider);
// set my network configuration
...
// set my default account and gas 
...
MyContract.new(["hello world"],[]).then(function (instance) { 
    addressNew = instance.address
    console.log("deployed: "+addressNew) 
    deployedCheck(addressNew) 
  }).catch(function (e) { 
    console.log(e) 
  });

```
Observations:
The console shows an empty string (below in the console after "hello contract:") by calling a function deployedCheck(addressNew) that uses the address of the newly created contract using at():

```
deployed: 0xec0d1e2d07d3c81bfd22eeac06115385577696f4
hello contract: 

```
It does not show different, when I re-read its state after a while.

**I checked reading the contracts state by creating a new contract with Truffle alternatively**. (deployer.deploy(Eternal, "hello world")) If I do I get the expected result. That indicates that the issue is with the creation by new() and not by reading the state.

**Comment by otembajelle** [comment]
I made the constructor above "payable". That made no difference though. I am stuck.

```
    function Eternal(string text) payable {
    	engravedText = text;
    }

```

**Comment by Manish166** [comment]
Hi,
Any update on this, @otembajelle I am also stuck at same place. Cannot pass parameter to my new contract. Did a get a fix for this?

**Comment by sarbao** [comment]
Mish166 me ttoo ... stuck there as well agggg !

**Comment by sarbao** [comment]
Manish166 ¡¡¡ I got it !! :-)

documentation is something confussimg. When you call.new(arguments) , the arguments it is not an array 

i was call Mycontract.new([arg1,arg2,arg3,arg5...]) without success

you have to put 

MyContract.new( arg1, arg2, arg3, arg5 ... ) and it wokrsd !!!!! :-)

best regards
