### ISSUE TITLE
MyContract.at upgrade to Promise

### ISSUE THREAD

**Issue by D-Nice** [trufflesuite/truffle-contract#55]
When will this method be upgraded to return a promise to be in line with the rest of this library? It's quite awkward (and was unexpected until I referred to the docs) that it returns a thenable object, especially when trying to work with es7 async/await.

**Comment by cgewecke** [comment]
@D-Nice Thanks for opening, apologies for the delay addressing this. We're going to track this issue at #88. Closing as duplicate.
