### ISSUE TITLE
.new() should validate constructor args

### ISSUE THREAD

**Issue by benjamincburns** [trufflesuite/truffle-contract#82]
I lost a fair amount of time writing tests the other day because I forgot to pass a constructor arg to `MyContract.new(...)`, and it was silently evaluated as `0x0`. An error similar to the one I get when I have an incorrect number of args to a solidity function would have saved me time here.

**Comment by cgewecke** [comment]
@benjamincburns Thanks! Excellent idea. This is in the new release, `4.0.6`
